#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

# ═══════════════════════════════════════════════════════════════════
# flompt Docker — zero source changes, all config via CLI / env vars
# ═══════════════════════════════════════════════════════════════════

usage() {
  cat <<EOF
Usage: bash start.sh [OPTIONS]

Options:
  --backend-port PORT   Backend host port        (default: 8000)
  --app-port PORT       App dev server host port (default: 5173)
  --api-key KEY         AI provider API key
  --provider PROVIDER   anthropic | openai | groq (default: groq)
  --model MODEL         AI model ID
  -h, --help            Show this help

Env vars:
  BACKEND_PORT, APP_PORT
  ANTHROPIC_API_KEY, OPENAI_API_KEY, GROQ_API_KEY

Examples:
  bash start.sh --backend-port 8080
  bash start.sh --api-key sk-ant-xxx --provider anthropic
  BACKEND_PORT=8001 bash start.sh
EOF
  exit 0
}

# ── Defaults ──────────────────────────────────────────────────────
BACKEND_PORT="${BACKEND_PORT:-8000}"
APP_PORT="${APP_PORT:-5173}"
API_KEY=""
AI_PROVIDER=""
AI_MODEL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --backend-port) BACKEND_PORT="$2"; shift 2 ;;
    --app-port)     APP_PORT="$2";     shift 2 ;;
    --api-key)      API_KEY="$2";      shift 2 ;;
    --provider)     AI_PROVIDER="$2";  shift 2 ;;
    --model)        AI_MODEL="$2";     shift 2 ;;
    -h|--help)      usage ;;
    *) echo "Unknown: $1"; usage ;;
  esac
done

# ── Ensure backend/.env exists ─────────────────────────────────────
if [[ ! -f backend/.env ]]; then
  cp backend/.env.example backend/.env
  echo "[start.sh] Created backend/.env from .env.example"
fi

# ── Inject API key ──────────────────────────────────────────────────
if [[ -n "$API_KEY" ]]; then
  provider="${AI_PROVIDER:-groq}"
  sed -i.bak '/^ANTHROPIC_API_KEY=/d' backend/.env 2>/dev/null; rm -f backend/.env.bak
  sed -i.bak '/^OPENAI_API_KEY=/d'    backend/.env 2>/dev/null; rm -f backend/.env.bak
  sed -i.bak '/^GROQ_API_KEY=/d'      backend/.env 2>/dev/null; rm -f backend/.env.bak
  sed -i.bak '/^AI_PROVIDER=/d'       backend/.env 2>/dev/null; rm -f backend/.env.bak
  sed -i.bak '/^AI_MODEL=/d'          backend/.env 2>/dev/null; rm -f backend/.env.bak

  case "$provider" in
    anthropic) echo "ANTHROPIC_API_KEY=$API_KEY" >> backend/.env ;;
    openai)    echo "OPENAI_API_KEY=$API_KEY"    >> backend/.env ;;
    groq)      echo "GROQ_API_KEY=$API_KEY"      >> backend/.env ;;
  esac
  echo "AI_PROVIDER=$provider" >> backend/.env
  [[ -n "$AI_MODEL" ]] && echo "AI_MODEL=$AI_MODEL" >> backend/.env
  echo "[start.sh] Wrote $provider API key to backend/.env"
fi

# ── Generate docker-compose.override.yml ───────────────────────────
# Fixes the original docker-compose.yml (which references ./frontend)
# without touching it. Also uses network_mode:service so the Vite
# proxy's hardcoded localhost:8000 reaches the backend container.
cat > docker-compose.override.yml <<EOF
# Auto-generated by start.sh — do not edit
services:
  backend:
    ports:
      - "${BACKEND_PORT}:8000"
      - "${APP_PORT}:5173"
    env_file:
      - path: ./backend/.env
        required: false

  frontend:
    build: ./app
    network_mode: "service:backend"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
EOF

echo "[start.sh] Generated docker-compose.override.yml"

# ── Start ──────────────────────────────────────────────────────────
export BACKEND_PORT APP_PORT

echo "╔══════════════════════════════════╗"
echo "║  flompt Docker (local dev)      ║"
echo "╠══════════════════════════════════╣"
echo "║  Backend → http://localhost:${BACKEND_PORT}"
echo "║  App     → http://localhost:${APP_PORT}"
echo "╚══════════════════════════════════╝"
echo ""

docker compose up -d --build
